updater:
# View all events in a logbook
logbook:
history:
config:
# Track the sun
sun:
discovery:
conversation:
frontend:

### Text to speech
tts:
  - platform: google

#device_tracker: !include device_tracker.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#http:
#  api_password: !secret r_http_password
http:
  api_password: !secret r_http_password
  ssl_certificate: !secret ssl_cert_dir
  ssl_key: !secret ssl_key_dir

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 2
  temperature_unit: C
  unit_system: metric
  time_zone: Europe/Stockholm
  customize:
    #LIGHTS
    light.tradfri_remote_control_1:
        hidden: true
        google_assistant: false
    light.tradfri_motion_sensor_2:
        hidden: true
        google_assistant: false
    light.all_hue_lights:
        hidden: true
        google_assistant: false
    light.lampa_matbord:
        google_assistant_name: "Bedroom light"
    light.lampa_soffa:
        google_assistant_name: "Coach light"
    #SENSORS
    sensor.temp_vardagsrum:
        hidden: true
    sensor.humidity_vardagsrum:
        hidden: true
    sensor.humidity_meter:
        homebridge_sensor_type: "humidity"
    sensor.motion_vardagsrum:
        friendly_name: "Motion Vardagsrum"
        device_class: motion
    sensor.main_door_open:
        friendly_name: "Entrance door"
        device_class: opening
    #SWITCHES
#    switch.julbelysning_1:
#       device_class: light
#       icon: mdi:lightbulb
#       assumed_state: false
#       google_assistant: true
#       google_assistant_type: light
#       google_assistant_name: "Christmas Light 1"
#    switch.julbelysning_2:
#       device_class: light
#       icon: mdi:lightbulb
#       assumed_state: false
#       google_assistant: true
#       google_assistant_type: light
#       google_assistant_name: "Christmas Light 2"
    switch.light_tv:
       device_class: light
       icon: mdi:lightbulb
       assumed_state: false
       google_assistant: true
       google_assistant_type: light
       google_assistant_name: "Light TV"
    switch.light_bedroom:
       device_class: light
       icon: mdi:lightbulb
       assumed_state: false
       google_assistant: true
       google_assistant_type: light
       google_assistant_name: "Light Bedroom"
    #GROUPS
    group.all_automations:
       google_assistant: false
    group.all_lights:
       google_assistant: false
    group.all_scripts:
       google_assistant: false
    group.all_switches:
       google_assistant: false

# Weather prediction
sensor:
  - platform: yr

####### SSL check sensor #############
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_check_command

######### Zigbee Sensor Setup ###########

###Motion sensor##############
  - platform: rest
    resource: http://192.168.1.136:80/api/homeassistant/sensors/2
    value_template: '{{ value_json.state.presence }}'
    name: motion_vardagsrum
    scan_interval: "00:02:00"

### Temp sensor##############
  - platform: rest
    resource: http://192.168.1.136:80/api/homeassistant/sensors/3
    value_template: '{{ value_json.state.temperature }}'
    name: temp_vardagsrum
    scan_interval: "00:02:00"
# -27315, 2147483647

  - platform: template
    sensors:
      temp_meter:
        value_template: "{{ (states.sensor.temp_vardagsrum.state | float / 100)|round(1)  }}"
        friendly_name: "Temperature Meter"
        unit_of_measurement: '°C'

##Humidity sensor##############
  - platform: rest
    resource: http://192.168.1.136:80/api/homeassistant/sensors/4
    value_template: '{{ value_json.state.humidity }}'
    name: humidity_vardagsrum
    scan_interval: "00:02:00"
# 0, 10000

  - platform: template
    sensors:
      humidity_meter:
        value_template: "{{ (states.sensor.humidity_vardagsrum.state | float / 100)|round(1) }}"
        friendly_name: "Humidity Meter"
        unit_of_measurement: '%'

###Door Sensor##############
  - platform: rest
    resource: http://192.168.1.136:80/api/homeassistant/sensors/5
    value_template: '{{ value_json.state.open }}'
    name: main_door_open
    scan_interval: "00:02:00"

########## ZIGBEE SETUP ##########
#light:
#  platform: hue
#  host: 192.168.1.136

deconz:
  host: 192.168.1.136
########## CAMERA SETUP ##########
camera:
  - platform: ffmpeg
    name: Vardagsrum
    input: -rtsp_transport tcp -i rtsp://192.168.1.202/unicast
    extra_arguments: -pred 1

########## TELLDUS INIT ###########
tellduslive:
  update_interval: 5
#  signal_repetitions: 3

########## GOOGLE ASSISTANT ###########
google_assistant:
  project_id: !secret g_project_id
  client_id: !secret g_client_id
  access_token: !secret g_access_token
  api_key: !secret g_api_key
  base_url: !secret ssl_base_url
  exposed_domains:
    - switch
    - light
    - group

########## SPOTIFY ###########
media_player:
  - platform: spotify
    client_id: !secret s_client_id
    client_secret: !secret s_client_secret

########## Node-Red ###########
panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: 'http://192.168.1.136:1880/'

########## Floorplan ###########
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

########## SCENES ############
# colortemp interval 154 - 500
# Brightness 0 - 254
scene:
  - name: Mysljus
    entities:
      light.lampa_matbord:
        state: on
        brightness: 127
        color_temp: 400
      light.lampa_soffa:
        state: on
        brightness: 127
        color_temp: 400
  - name: Dagsbelysning
    entities:
      light.lampa_matbord:
        state: on
        brightness: 254
        color_temp: 170
      light.lampa_soffa:
        state: on
        brightness: 254
        color_temp: 170
